### ISSUE TITLE
Assembler and deep level

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/UI-DSM#24]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the UI-DSM
- [x] I have searched [open](https://github.com/RHEAGROUP/UI-DSM/issues) and [closed](https://github.com/RHEAGROUP/UI-DSM/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

To exchange information between the server and the client, a flat list of DTOs should be transfer.
The deep level will define how deep we want to get the associated entities for queries.
The assembler will take care of resolving properties from the flat list of DTOs to create POCOs
### System Configuration

- UI-DSM version:
  - [ ] UI-DSM:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by lxatrhea** [comment]
@antoineatrhea Be careful with the deeplevel option. A deeplevel of 1 probably gets more data that extected ==> decreased performance. Deeplevel 2 probably needs to get half of the whole database. I expect that you need more fine grained information.
The reason for this is that we expect full DTO's. In practice in most cases we probably need partial DTO data and we don't need most of the "linked" GUID's from the UI's perspective. That's why sending full DTO's (99% equal to the database representation) isn't good practise for this.

@samatrhea I think we should discuss this: Either use the Entity Framewok way, which means we create specific classes (not DTO's) that will be sent to the UI that contains only the data that the UI needs, or we do the COMET way and then we need to think about how to handle all the referenced data in DTO's. We need to do a LEFT JOIN to get all the referenced GUID's for all the DTO's the are sent back. Which in a deeplevel of 1 results in deeplevel 2 calls to be made to get all those referenced GUID's
